---
- name: Remove useless line ::1 for correct pcs cluster in file in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^::1'
    state: absent

- name: Remove useless line 127.0.0.1 for correct pcs cluster in file /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    state: absent

- name: Build hosts file
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].inventory_hostname }} {{ hostvars[item].cluster_host }}"
    state: present
  with_items: "{{ groups.all }}"
